services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sws
      POSTGRES_USER: sws_user
      POSTGRES_PASSWORD: sws_pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sws_user -d sws" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sws
      SPRING_DATASOURCE_USERNAME: sws_user
      SPRING_DATASOURCE_PASSWORD: sws_pass
      SPRING_FLYWAY_ENABLED:    "true"

volumes:
  pgdata:
