spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    root: DEBUG
    com.rissatto: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
